### ISSUE TITLE
Can you build & Publish utilities (cmdline magick)

### ISSUE THREAD

**Issue by KnicKnic** [dlemstra/Magick.Native#1]
Would it be possible to publish the cmdline magick.wasm and magick.js ? Unfortunately I made an attempt at this and failed. 

After many simple attempts, I just ended up with a total hack on the code which I thought would work but didn't. You can see my attempt here https://github.com/KnicKnic/Magick.Native/tree/compile_fix

I say I failed because the code through an exception trying to process a 3MB png.

```
magick.js:32 exception thrown: RangeError: Invalid typed array length: undefined,RangeError: Invalid typed array length: undefined
    at new Int8Array (<anonymous>)
    at updateGlobalBufferViews (https://knicknic.github.io/imagemagick/test/magick.js:1341:29)
    at _emscripten_resize_heap (https://knicknic.github.io/imagemagick/test/magick.js:8747:7)
    at wasm-function[8949]:64
    at wasm-function[8164]:7263
    at wasm-function[8171]:187
    at wasm-function[8172]:166
    at wasm-function[391]:123
    at wasm-function[1538]:2022
    at wasm-function[1536]:1760
printErr @ magick.js:32
callMain @ magick.js:11246
processFiles @ magick.js:75
onmessage @ magick.js:128
```

**Comment by dlemstra** [comment]
There is a `build.cmd` file that you could use to build the library and copy the output of the project.

**Comment by dlemstra** [comment]
This library is published here: https://www.npmjs.com/package/@imagemagick/magick-wasm
