### ISSUE TITLE
Auth enabled for npm module @dlemstra/magick-native 401 Unauthorized?

### ISSUE THREAD

**Issue by reggi** [dlemstra/Magick.Native#29]
Hey @dlemstra I'm curious why this module has been made private? Was trying to make an update to https://github.com/lumeland/imagemagick-deno/tree/main/deno to add the new `DrawableTextKerning` 😸

**Comment by dlemstra** [comment]
It has not been made private, otherwise you would not be able to start this issue. I suspect that your GITHUB token has been expired and needs a refresh?
