### ISSUE TITLE
Incorrect Memory Limits with cgroups v2

### ISSUE THREAD

**Issue by pinkfloydx33** [dlemstra/Magick.Native#53]
I'm not sure how exactly this library determines the maximum available memory on Linux, but in container scenarios it's at least _sometimes_  incorrect.

We are running Azure Kubernetes backed by `containerd` (if that matters). We have noticed that, rather than returning the memory indicated by the cgroups (v2) file `/sys/fs/cgroup/memory.max`, that calls into `ResourceLimits_LimitMemory` (made via Magick.NET's `ResourceLimits.LimitMemory`) are returning the _equivalent_ of `/proc/meminfo`

What this means is that instead of seeing the `~300mb` memory limit the container has been assigned, the library sees the `30gb` memory of the _underlying VM_. The default 50% limit therefore equates to `15gb` which is `14.5gb+` _more_ than the container actually has available. This has led to situations where Kubernetes OOM kills our pods during a relatively low load of thumbnail generation in a short period of time. 

I'm not a Linux expert so I don't know exactly how one is supposed to detect such a case, but there's clearly a way. I'm also unsure if this is limited to containers or is more broadly impacting Linux. I believe that it has to be handled on the native side, hence the bug report.

For reference, I've posted in the Magick.NET repo, documenting what led me here (with some other open questions, hence being a discussion).

https://github.com/dlemstra/Magick.NET/discussions/1744

**Comment by dlemstra** [comment]
Please don't open both an issue and a discussion for the same thing. Next time please add a comment to that discussion with the extra research that you have done.
