### ISSUE TITLE
OpenMP Support

### ISSUE THREAD

**Issue by cmsppl** [dlemstra/Magick.Native#7]
Hi dlemstra,

Thanks for all your work.

I built Magick.Native Dockerfile so that I can build an OpenMP version for linux.

I took out --disable-openmp from the configuration and added -fopenmp flag to the compiler flags.

But I still get omp_init error.

Is OpenMP just not supported on linux at the moment? I see in your package releases that none of the linux releases have OpenMP on it. Am I trying to do something that's just not possible at this time, or am I missing something silly?

I would really appreciate any guidance on getting libMagick.Native-Q8-OpenMP-x64.dll.so for linux.

Thanks in advance!

**Comment by dlemstra** [comment]
There is no OpenMP support for Linux at the moment. The OpenMP library would need to be statically linked. I have not made time to investigate how to get that working.

**Comment by cmsppl** [comment]
Thanks for clearing that up. Spent almost two days scratching my head. Back to Windows!

**Comment by cmsppl** [comment]
Hi dlemstra, 

It's been a few months. It seems this will never get looked at, although I think many will find it useful, anyways I could save some money on windows licensing fees if this works. Is there any way I could put a bounty on this?

Thanks!

**Comment by dlemstra** [comment]
GitHub has no support for putting a bounty on an issue. I do tend to prioritize issues from sponsors that I have on GitHub. But this comes with no garuantees.

**Comment by cmsppl** [comment]
We became a sponsor. We cannot sponsor you at this rate on an ongoing basis forever, but if you can make OpenMP work on linux, I'll make sure to keep sponsoring your work for at least another month. If not, you deserve at least this much from us anyways. I feel like this would be something that is very easy for you, so I hope you can make it happen, and I'm sure others would find this useful as well. Thanks for all your work. We really appreciate it.

**Comment by dlemstra** [comment]
Thanks for sponsoring me. If this was easy I would have done that a lot earlier. Will try to take a look at it this weekend.

**Comment by dlemstra** [comment]
Turns out that it is not recommended to static link the openmp library. While writing this a GitHub actions build is running that will add OpenMP support for Linux. It will require you to install `libgomp1`.

**Comment by cmsppl** [comment]
Thanks again for all your work. It works great! Keep up the great work!

**Comment by dlemstra** [comment]
How are you using this library? Are you not using it through Magick.NET?

**Comment by cmsppl** [comment]
We are using it through Magick.NET. Why?

**Comment by dlemstra** [comment]
I was suspecting that but because you already tested it I was wondering if you used it another way.

**Comment by cmsppl** [comment]
Oh I see. Yes, I didn't need to make any changes. I just swapped out the library file, and it just worked.
