### ISSUE TITLE
No Decode Delegate for OpenRaster (ORA) - Add libzip Delegate

### ISSUE THREAD

**Issue by SethFalco** [dlemstra/Magick.Native#8]
Currently, it seems we're unable to read the ORA format in Magick.NET because the `libzip` delegate wasn't added.

> To make it possible to read this format in the Magick.NET library or with ImageMagick you need the libzip delegate.

References: https://github.com/ImageMagick/ImageMagick/discussions/3184

**Comment by dlemstra** [comment]
Support for this was just added to the new release of Magick.NET.
